### ISSUE TITLE
Missing ?

### ISSUE THREAD

**Issue by Cool19094** [bgromov/ros_qml#1]
I cant get the :
$ python configure.py --sip-incdir=/usr/include/python2.7/ --qmake=/opt/qt54/bin/qmake 
to work, 
python : can't open file 'configure.py' : [Error 2] No such file or directory

**Comment by bgromov** [comment]
This command is to configure PyQt, so you have to execute it in PyQt source folder.

Have a look here: http://pyqt.sourceforge.net/Docs/PyQt5/installation.html#building-and-installing-from-source
